### ISSUE TITLE
Can this method process voice real-time?  

### ISSUE THREAD

**Issue by ericleee0119** [SamuelBroughton/StarGAN-Voice-Conversion-2#10]
Hi, thank you for sharing the project.
I would like to know about if this method is able to process voice real-time?
For example, I speak with my microphone, and output the new voice in a short time without waiting for a long processing time.
If not, do you know any method about this?
Thank you.

**Comment by shackysureshot** [comment]
No this is not possible, the model also does not generalise to voices it has not heard before. I do not know of current methods that do this.
