### ISSUE TITLE
Can you provide any pretrained models?

### ISSUE THREAD

**Issue by vnyk** [SamuelBroughton/StarGAN-Voice-Conversion-2#2]

**Comment by shackysureshot** [comment]
Pretrained models and any converted samples will be up around a months time

**Comment by marlon-br** [comment]
any updates here?

**Comment by avilash** [comment]
@SamuelBroughton - any updates ?

**Comment by shackysureshot** [comment]
Included samples but not model checkpoints, commit https://github.com/SamuelBroughton/StarGAN-Voice-Conversion-2/commit/26484a2db5a00247535c7ec7c1f97c10e711e022
