### ISSUE TITLE
when i use your code , the loss is nan 

### ISSUE THREAD

**Issue by xudongxiang** [SamuelBroughton/StarGAN-Voice-Conversion-2#4]
![图片](https://user-images.githubusercontent.com/36840203/79943286-15471a00-849b-11ea-8008-b57b6b4a805e.png)

**Comment by codeplay13** [comment]
I am also getting nan as the loss. Did you train till 200000 iterations?

**Comment by shackysureshot** [comment]
Hi yes currently it needs to be set off a couple of times to find the gradients properly otherwise it can get stuck. I have been working on this and am getting better results to be pushed soon. Everything is taking a little longer due to the current crisis, i hope you understand!

**Comment by codeplay13** [comment]
So restarting the training until we get some proper (not nan) values solves this?

> Hi yes currently it needs to be set off a couple of times to find the gradients properly otherwise it can get stuck. I have been working on this and am getting better results to be pushed soon. Everything is taking a little longer due to the current crisis, i hope you understand!

**Comment by shackysureshot** [comment]
Yeah, not ideal I know! but i do have changes waiting to push

**Comment by codeplay13** [comment]
Okay. Thanks for clarifying.
