### ISSUE TITLE
Requirements for speaker data

### ISSUE THREAD

**Issue by marlon-br** [SamuelBroughton/StarGAN-Voice-Conversion-2#6]
What is a minimum amount of input voice data for every speaker required to get good results?
As per original paper: "Each speaker has sets of 81 and 35 sentences for training and evaluation, respectively". I wonder if it possible to train model and get better results with less phrases?

**Comment by shackysureshot** [comment]
Hi @marlon-br I havent investigated specifically the minimum amount of voice input data to achieve good results however, obviously with more data better conversion is achieved. As seen in this repo when training the data on VCTK (larger set) and VCC2018 (smaller set).
