### ISSUE TITLE
Error on test when training, generator takes only 2 arguments

### ISSUE THREAD

**Issue by lowoodz** [SamuelBroughton/StarGAN-Voice-Conversion-2#7]
`coded_sp_converted_norm = self.generator(coded_sp_norm_tensor, org_conds, conds).data.cpu().numpy()`

why pass org_conds as an argument?

**Comment by shackysureshot** [comment]
Apologies, I forgot to remove that in the update, see latest commit https://github.com/SamuelBroughton/StarGAN-Voice-Conversion-2/commit/233cac6d0b42c79787e4e3608a0f100fa5d8fedb
